name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 1-检出代码
      uses: actions/checkout@v3
    - name: 2-安装pnpm
      uses: pnpm/action-setup@v2.2.2
      with:
        version: 7.18.0
    - name: 3-安装依赖
      run: pnpm install
    - name: 4-编译
      run: pnpm run build
    - name: 5-将代码上传到gh-page分支
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist
    
